version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - filipdujmusic
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.3
  - dependency-name: lodash
    versions:
    - 4.17.20
