# https://docs.aeternity.io/en/latest/configuration/

---
peers: []

http:
    external:
        port: 3013
    internal:
        port: 3113
        listen_address: 0.0.0.0
        debug_endpoints: true

websocket:
    channel:
        port: 3014
        listen_address: 0.0.0.0

chain:
    persist: true
    hard_forks:
        "1": 0
        "2": 2
        "3": 4
        "4": 6

mining:
    beneficiary: "ak_twR4h7dEcUtc2iSEDv8kB7UFJJDGiEDQCXr85C3fYF8FdVdyo"
    beneficiary_reward_delay: 2
    autostart: true
    expected_mine_rate: 500
    micro_block_cycle: 100
    cuckoo:
        edge_bits: 15
        miners:
            - executable: mean15-generic

fork_management:
    network_id: ae_docker